CREATE TABLE `bank` (
    `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `nick` VARCHAR(100) NOT NULL DEFAULT '',
    `ts` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `treasure` INT NOT NULL DEFAULT 0,
    PRIMARY KEY(`id`),
    INDEX `user_idx` (`user_id`)
) ENGINE=InnoDB Default CHARSET=utf8mb4;

CREATE TABLE `users` (
    `id` BIGINT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `nick` VARCHAR(100) NOT NULL DEFAULT '',
    `created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`)
) ENGINE=InnoDB Default CHARSET=utf8mb4;